name: Executar Robo B3 Diario

on:
  schedule:
    # 14:40 UTC equivale às 11:40 no Horário de Brasília
    - cron: '40 14 * * 1-5'
    # 22:00 UTC equivale às 19:00 no Horário de Brasília
    - cron: '0 22 * * 1-5'
  workflow_dispatch: # Permite que você clique em um botão para testar quando quiser

jobs:
  rodar-robo:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar codigo do repositorio
      uses: actions/checkout@v3

    - name: Configurar o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar as ferramentas financeiras
      run: |
        pip install yfinance pandas numpy pytz

    - name: Rodar a Inteligência Artificial da B3
      run: python robo_b3.py
